_wandb:
    value:
        cli_version: 0.21.0
        e:
            h69nokld1mylyfr2h6s4h08xv90r0lh5:
                args:
                    - --model
                    - Qwen/Qwen3-1.7B
                    - --model_class
                    - qwen3
                    - --nproc
                    - "1"
                    - --batch_size
                    - "4"
                    - --max_len
                    - "32768"
                    - --gen_len
                    - "30768"
                    - --output_dir
                    - Qwen3-1.7B
                    - --task
                    - aime24
                codePath: examples/ref_hf.py
                codePathLocal: ref_hf.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "322055438336"
                        used: "109381025792"
                email: chenzhuoming911@gmail.com
                executable: /home/zhuominc/anaconda3/envs/lite/bin/python
                git:
                    commit: 0a79fd93491db8da0f1fb3e519249c0f8aef2f27
                    remote: https://github.com/Infini-AI-Lab/litesys.git
                gpu: NVIDIA L40
                gpu_count: 10
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-c22ef825-1665-183e-d372-8dc1aca1d9cf
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-25ea90bf-1137-31e2-fe79-a47827da1cf9
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-41641f8e-5d82-e183-5183-adca69a7d376
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-603ac6ab-5195-ff5c-37e4-823eafbdd4ac
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-cb7f4e31-6ed6-2b9a-e5ee-793a7b77c6a7
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-b9c15f98-fd91-8f28-219d-34878052b1c2
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-e3b1f0d0-ceaa-0c8d-e602-9e5d17a77cda
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-b0512c31-11b3-b62b-07ce-00e8c376eb63
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-afd74ba8-780e-2a71-e302-afb214341c9e
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-f9e8b221-f9a0-23ed-774c-e7d0263bf708
                host: lovelace.ece.local.cmu.edu
                memory:
                    total: "2163569283072"
                os: Linux-5.14.0-503.16.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: /home/zhuominc/litesys-oss/litesys/examples/ref_hf.py
                python: CPython 3.11.13
                root: /home/zhuominc/litesys-oss/litesys/examples
                startedAt: "2025-07-09T03:03:26.396879Z"
                writerId: h69nokld1mylyfr2h6s4h08xv90r0lh5
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.51.0
            "8":
                - 2
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 4
gen_len:
    value: 30768
max_len:
    value: 32768
model:
    value: Qwen/Qwen3-1.7B
model_class:
    value: qwen3
nproc:
    value: 1
output_dir:
    value: Qwen3-1.7B
task:
    value: aime24
